### ISSUE TITLE
Tracking: Benchmark suffix array index

### ISSUE THREAD

**Issue by tibvdm** [unipept/unipept-index#4]
```[tasklist]
### Tasks
- [ ] https://github.com/unipept/unipept-index/issues/5
- [ ] https://github.com/unipept/unipept-index/issues/6
- [ ] https://github.com/unipept/unipept-index/issues/7
```
